// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kyc_service/ent/kyc"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Kyc is the model entity for the Kyc schema.
type Kyc struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// IDCardNumber holds the value of the "id_card_number" field.
	IDCardNumber *string `json:"id_card_number,omitempty"`
	// LicenseNumber holds the value of the "license_number" field.
	LicenseNumber *string `json:"license_number,omitempty"`
	// IDCardFrontURL holds the value of the "id_card_front_url" field.
	IDCardFrontURL string `json:"id_card_front_url,omitempty"`
	// IDCardBackURL holds the value of the "id_card_back_url" field.
	IDCardBackURL string `json:"id_card_back_url,omitempty"`
	// LicenseFrontURL holds the value of the "license_front_url" field.
	LicenseFrontURL string `json:"license_front_url,omitempty"`
	// LicenseBackURL holds the value of the "license_back_url" field.
	LicenseBackURL string `json:"license_back_url,omitempty"`
	// Status holds the value of the "status" field.
	Status kyc.Status `json:"status,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy *uuid.UUID `json:"reviewed_by,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Kyc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kyc.FieldReviewedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case kyc.FieldIDCardNumber, kyc.FieldLicenseNumber, kyc.FieldIDCardFrontURL, kyc.FieldIDCardBackURL, kyc.FieldLicenseFrontURL, kyc.FieldLicenseBackURL, kyc.FieldStatus, kyc.FieldNote:
			values[i] = new(sql.NullString)
		case kyc.FieldReviewedAt, kyc.FieldCreatedAt, kyc.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case kyc.FieldID, kyc.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Kyc fields.
func (_m *Kyc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kyc.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case kyc.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case kyc.FieldIDCardNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card_number", values[i])
			} else if value.Valid {
				_m.IDCardNumber = new(string)
				*_m.IDCardNumber = value.String
			}
		case kyc.FieldLicenseNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_number", values[i])
			} else if value.Valid {
				_m.LicenseNumber = new(string)
				*_m.LicenseNumber = value.String
			}
		case kyc.FieldIDCardFrontURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card_front_url", values[i])
			} else if value.Valid {
				_m.IDCardFrontURL = value.String
			}
		case kyc.FieldIDCardBackURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card_back_url", values[i])
			} else if value.Valid {
				_m.IDCardBackURL = value.String
			}
		case kyc.FieldLicenseFrontURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_front_url", values[i])
			} else if value.Valid {
				_m.LicenseFrontURL = value.String
			}
		case kyc.FieldLicenseBackURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_back_url", values[i])
			} else if value.Valid {
				_m.LicenseBackURL = value.String
			}
		case kyc.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = kyc.Status(value.String)
			}
		case kyc.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case kyc.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = new(uuid.UUID)
				*_m.ReviewedBy = *value.S.(*uuid.UUID)
			}
		case kyc.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case kyc.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case kyc.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Kyc.
// This includes values selected through modifiers, order, etc.
func (_m *Kyc) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Kyc.
// Note that you need to call Kyc.Unwrap() before calling this method if this Kyc
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Kyc) Update() *KycUpdateOne {
	return NewKycClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Kyc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Kyc) Unwrap() *Kyc {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Kyc is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Kyc) String() string {
	var builder strings.Builder
	builder.WriteString("Kyc(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.IDCardNumber; v != nil {
		builder.WriteString("id_card_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LicenseNumber; v != nil {
		builder.WriteString("license_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("id_card_front_url=")
	builder.WriteString(_m.IDCardFrontURL)
	builder.WriteString(", ")
	builder.WriteString("id_card_back_url=")
	builder.WriteString(_m.IDCardBackURL)
	builder.WriteString(", ")
	builder.WriteString("license_front_url=")
	builder.WriteString(_m.LicenseFrontURL)
	builder.WriteString(", ")
	builder.WriteString("license_back_url=")
	builder.WriteString(_m.LicenseBackURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	if v := _m.ReviewedBy; v != nil {
		builder.WriteString("reviewed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Kycs is a parsable slice of Kyc.
type Kycs []*Kyc
