// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kyc_service/ent/kyc"
	"kyc_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// KycUpdate is the builder for updating Kyc entities.
type KycUpdate struct {
	config
	hooks    []Hook
	mutation *KycMutation
}

// Where appends a list predicates to the KycUpdate builder.
func (_u *KycUpdate) Where(ps ...predicate.Kyc) *KycUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KycUpdate) SetUserID(v uuid.UUID) *KycUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KycUpdate) SetNillableUserID(v *uuid.UUID) *KycUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIDCardNumber sets the "id_card_number" field.
func (_u *KycUpdate) SetIDCardNumber(v string) *KycUpdate {
	_u.mutation.SetIDCardNumber(v)
	return _u
}

// SetNillableIDCardNumber sets the "id_card_number" field if the given value is not nil.
func (_u *KycUpdate) SetNillableIDCardNumber(v *string) *KycUpdate {
	if v != nil {
		_u.SetIDCardNumber(*v)
	}
	return _u
}

// ClearIDCardNumber clears the value of the "id_card_number" field.
func (_u *KycUpdate) ClearIDCardNumber() *KycUpdate {
	_u.mutation.ClearIDCardNumber()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *KycUpdate) SetLicenseNumber(v string) *KycUpdate {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *KycUpdate) SetNillableLicenseNumber(v *string) *KycUpdate {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *KycUpdate) ClearLicenseNumber() *KycUpdate {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetIDCardFrontURL sets the "id_card_front_url" field.
func (_u *KycUpdate) SetIDCardFrontURL(v string) *KycUpdate {
	_u.mutation.SetIDCardFrontURL(v)
	return _u
}

// SetNillableIDCardFrontURL sets the "id_card_front_url" field if the given value is not nil.
func (_u *KycUpdate) SetNillableIDCardFrontURL(v *string) *KycUpdate {
	if v != nil {
		_u.SetIDCardFrontURL(*v)
	}
	return _u
}

// ClearIDCardFrontURL clears the value of the "id_card_front_url" field.
func (_u *KycUpdate) ClearIDCardFrontURL() *KycUpdate {
	_u.mutation.ClearIDCardFrontURL()
	return _u
}

// SetIDCardBackURL sets the "id_card_back_url" field.
func (_u *KycUpdate) SetIDCardBackURL(v string) *KycUpdate {
	_u.mutation.SetIDCardBackURL(v)
	return _u
}

// SetNillableIDCardBackURL sets the "id_card_back_url" field if the given value is not nil.
func (_u *KycUpdate) SetNillableIDCardBackURL(v *string) *KycUpdate {
	if v != nil {
		_u.SetIDCardBackURL(*v)
	}
	return _u
}

// ClearIDCardBackURL clears the value of the "id_card_back_url" field.
func (_u *KycUpdate) ClearIDCardBackURL() *KycUpdate {
	_u.mutation.ClearIDCardBackURL()
	return _u
}

// SetLicenseFrontURL sets the "license_front_url" field.
func (_u *KycUpdate) SetLicenseFrontURL(v string) *KycUpdate {
	_u.mutation.SetLicenseFrontURL(v)
	return _u
}

// SetNillableLicenseFrontURL sets the "license_front_url" field if the given value is not nil.
func (_u *KycUpdate) SetNillableLicenseFrontURL(v *string) *KycUpdate {
	if v != nil {
		_u.SetLicenseFrontURL(*v)
	}
	return _u
}

// ClearLicenseFrontURL clears the value of the "license_front_url" field.
func (_u *KycUpdate) ClearLicenseFrontURL() *KycUpdate {
	_u.mutation.ClearLicenseFrontURL()
	return _u
}

// SetLicenseBackURL sets the "license_back_url" field.
func (_u *KycUpdate) SetLicenseBackURL(v string) *KycUpdate {
	_u.mutation.SetLicenseBackURL(v)
	return _u
}

// SetNillableLicenseBackURL sets the "license_back_url" field if the given value is not nil.
func (_u *KycUpdate) SetNillableLicenseBackURL(v *string) *KycUpdate {
	if v != nil {
		_u.SetLicenseBackURL(*v)
	}
	return _u
}

// ClearLicenseBackURL clears the value of the "license_back_url" field.
func (_u *KycUpdate) ClearLicenseBackURL() *KycUpdate {
	_u.mutation.ClearLicenseBackURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KycUpdate) SetStatus(v kyc.Status) *KycUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KycUpdate) SetNillableStatus(v *kyc.Status) *KycUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *KycUpdate) SetNote(v string) *KycUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *KycUpdate) SetNillableNote(v *string) *KycUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *KycUpdate) ClearNote() *KycUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *KycUpdate) SetReviewedBy(v uuid.UUID) *KycUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *KycUpdate) SetNillableReviewedBy(v *uuid.UUID) *KycUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *KycUpdate) ClearReviewedBy() *KycUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *KycUpdate) SetReviewedAt(v time.Time) *KycUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *KycUpdate) SetNillableReviewedAt(v *time.Time) *KycUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *KycUpdate) ClearReviewedAt() *KycUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KycUpdate) SetUpdatedAt(v time.Time) *KycUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KycMutation object of the builder.
func (_u *KycUpdate) Mutation() *KycMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KycUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KycUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KycUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KycUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KycUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kyc.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KycUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := kyc.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Kyc.status": %w`, err)}
		}
	}
	return nil
}

func (_u *KycUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kyc.Table, kyc.Columns, sqlgraph.NewFieldSpec(kyc.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kyc.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IDCardNumber(); ok {
		_spec.SetField(kyc.FieldIDCardNumber, field.TypeString, value)
	}
	if _u.mutation.IDCardNumberCleared() {
		_spec.ClearField(kyc.FieldIDCardNumber, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(kyc.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(kyc.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.IDCardFrontURL(); ok {
		_spec.SetField(kyc.FieldIDCardFrontURL, field.TypeString, value)
	}
	if _u.mutation.IDCardFrontURLCleared() {
		_spec.ClearField(kyc.FieldIDCardFrontURL, field.TypeString)
	}
	if value, ok := _u.mutation.IDCardBackURL(); ok {
		_spec.SetField(kyc.FieldIDCardBackURL, field.TypeString, value)
	}
	if _u.mutation.IDCardBackURLCleared() {
		_spec.ClearField(kyc.FieldIDCardBackURL, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseFrontURL(); ok {
		_spec.SetField(kyc.FieldLicenseFrontURL, field.TypeString, value)
	}
	if _u.mutation.LicenseFrontURLCleared() {
		_spec.ClearField(kyc.FieldLicenseFrontURL, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseBackURL(); ok {
		_spec.SetField(kyc.FieldLicenseBackURL, field.TypeString, value)
	}
	if _u.mutation.LicenseBackURLCleared() {
		_spec.ClearField(kyc.FieldLicenseBackURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kyc.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(kyc.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(kyc.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(kyc.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(kyc.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(kyc.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(kyc.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kyc.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kyc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KycUpdateOne is the builder for updating a single Kyc entity.
type KycUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KycMutation
}

// SetUserID sets the "user_id" field.
func (_u *KycUpdateOne) SetUserID(v uuid.UUID) *KycUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableUserID(v *uuid.UUID) *KycUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIDCardNumber sets the "id_card_number" field.
func (_u *KycUpdateOne) SetIDCardNumber(v string) *KycUpdateOne {
	_u.mutation.SetIDCardNumber(v)
	return _u
}

// SetNillableIDCardNumber sets the "id_card_number" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableIDCardNumber(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetIDCardNumber(*v)
	}
	return _u
}

// ClearIDCardNumber clears the value of the "id_card_number" field.
func (_u *KycUpdateOne) ClearIDCardNumber() *KycUpdateOne {
	_u.mutation.ClearIDCardNumber()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *KycUpdateOne) SetLicenseNumber(v string) *KycUpdateOne {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableLicenseNumber(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *KycUpdateOne) ClearLicenseNumber() *KycUpdateOne {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetIDCardFrontURL sets the "id_card_front_url" field.
func (_u *KycUpdateOne) SetIDCardFrontURL(v string) *KycUpdateOne {
	_u.mutation.SetIDCardFrontURL(v)
	return _u
}

// SetNillableIDCardFrontURL sets the "id_card_front_url" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableIDCardFrontURL(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetIDCardFrontURL(*v)
	}
	return _u
}

// ClearIDCardFrontURL clears the value of the "id_card_front_url" field.
func (_u *KycUpdateOne) ClearIDCardFrontURL() *KycUpdateOne {
	_u.mutation.ClearIDCardFrontURL()
	return _u
}

// SetIDCardBackURL sets the "id_card_back_url" field.
func (_u *KycUpdateOne) SetIDCardBackURL(v string) *KycUpdateOne {
	_u.mutation.SetIDCardBackURL(v)
	return _u
}

// SetNillableIDCardBackURL sets the "id_card_back_url" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableIDCardBackURL(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetIDCardBackURL(*v)
	}
	return _u
}

// ClearIDCardBackURL clears the value of the "id_card_back_url" field.
func (_u *KycUpdateOne) ClearIDCardBackURL() *KycUpdateOne {
	_u.mutation.ClearIDCardBackURL()
	return _u
}

// SetLicenseFrontURL sets the "license_front_url" field.
func (_u *KycUpdateOne) SetLicenseFrontURL(v string) *KycUpdateOne {
	_u.mutation.SetLicenseFrontURL(v)
	return _u
}

// SetNillableLicenseFrontURL sets the "license_front_url" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableLicenseFrontURL(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetLicenseFrontURL(*v)
	}
	return _u
}

// ClearLicenseFrontURL clears the value of the "license_front_url" field.
func (_u *KycUpdateOne) ClearLicenseFrontURL() *KycUpdateOne {
	_u.mutation.ClearLicenseFrontURL()
	return _u
}

// SetLicenseBackURL sets the "license_back_url" field.
func (_u *KycUpdateOne) SetLicenseBackURL(v string) *KycUpdateOne {
	_u.mutation.SetLicenseBackURL(v)
	return _u
}

// SetNillableLicenseBackURL sets the "license_back_url" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableLicenseBackURL(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetLicenseBackURL(*v)
	}
	return _u
}

// ClearLicenseBackURL clears the value of the "license_back_url" field.
func (_u *KycUpdateOne) ClearLicenseBackURL() *KycUpdateOne {
	_u.mutation.ClearLicenseBackURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KycUpdateOne) SetStatus(v kyc.Status) *KycUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableStatus(v *kyc.Status) *KycUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *KycUpdateOne) SetNote(v string) *KycUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableNote(v *string) *KycUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *KycUpdateOne) ClearNote() *KycUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *KycUpdateOne) SetReviewedBy(v uuid.UUID) *KycUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableReviewedBy(v *uuid.UUID) *KycUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *KycUpdateOne) ClearReviewedBy() *KycUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *KycUpdateOne) SetReviewedAt(v time.Time) *KycUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *KycUpdateOne) SetNillableReviewedAt(v *time.Time) *KycUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *KycUpdateOne) ClearReviewedAt() *KycUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KycUpdateOne) SetUpdatedAt(v time.Time) *KycUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KycMutation object of the builder.
func (_u *KycUpdateOne) Mutation() *KycMutation {
	return _u.mutation
}

// Where appends a list predicates to the KycUpdate builder.
func (_u *KycUpdateOne) Where(ps ...predicate.Kyc) *KycUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KycUpdateOne) Select(field string, fields ...string) *KycUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Kyc entity.
func (_u *KycUpdateOne) Save(ctx context.Context) (*Kyc, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KycUpdateOne) SaveX(ctx context.Context) *Kyc {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KycUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KycUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KycUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kyc.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KycUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := kyc.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Kyc.status": %w`, err)}
		}
	}
	return nil
}

func (_u *KycUpdateOne) sqlSave(ctx context.Context) (_node *Kyc, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kyc.Table, kyc.Columns, sqlgraph.NewFieldSpec(kyc.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Kyc.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kyc.FieldID)
		for _, f := range fields {
			if !kyc.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kyc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kyc.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IDCardNumber(); ok {
		_spec.SetField(kyc.FieldIDCardNumber, field.TypeString, value)
	}
	if _u.mutation.IDCardNumberCleared() {
		_spec.ClearField(kyc.FieldIDCardNumber, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(kyc.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(kyc.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.IDCardFrontURL(); ok {
		_spec.SetField(kyc.FieldIDCardFrontURL, field.TypeString, value)
	}
	if _u.mutation.IDCardFrontURLCleared() {
		_spec.ClearField(kyc.FieldIDCardFrontURL, field.TypeString)
	}
	if value, ok := _u.mutation.IDCardBackURL(); ok {
		_spec.SetField(kyc.FieldIDCardBackURL, field.TypeString, value)
	}
	if _u.mutation.IDCardBackURLCleared() {
		_spec.ClearField(kyc.FieldIDCardBackURL, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseFrontURL(); ok {
		_spec.SetField(kyc.FieldLicenseFrontURL, field.TypeString, value)
	}
	if _u.mutation.LicenseFrontURLCleared() {
		_spec.ClearField(kyc.FieldLicenseFrontURL, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseBackURL(); ok {
		_spec.SetField(kyc.FieldLicenseBackURL, field.TypeString, value)
	}
	if _u.mutation.LicenseBackURLCleared() {
		_spec.ClearField(kyc.FieldLicenseBackURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kyc.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(kyc.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(kyc.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(kyc.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(kyc.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(kyc.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(kyc.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kyc.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Kyc{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kyc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
