// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kyc_service/ent/kyc"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// KycCreate is the builder for creating a Kyc entity.
type KycCreate struct {
	config
	mutation *KycMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *KycCreate) SetUserID(v uuid.UUID) *KycCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIDCardNumber sets the "id_card_number" field.
func (_c *KycCreate) SetIDCardNumber(v string) *KycCreate {
	_c.mutation.SetIDCardNumber(v)
	return _c
}

// SetNillableIDCardNumber sets the "id_card_number" field if the given value is not nil.
func (_c *KycCreate) SetNillableIDCardNumber(v *string) *KycCreate {
	if v != nil {
		_c.SetIDCardNumber(*v)
	}
	return _c
}

// SetLicenseNumber sets the "license_number" field.
func (_c *KycCreate) SetLicenseNumber(v string) *KycCreate {
	_c.mutation.SetLicenseNumber(v)
	return _c
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_c *KycCreate) SetNillableLicenseNumber(v *string) *KycCreate {
	if v != nil {
		_c.SetLicenseNumber(*v)
	}
	return _c
}

// SetIDCardFrontURL sets the "id_card_front_url" field.
func (_c *KycCreate) SetIDCardFrontURL(v string) *KycCreate {
	_c.mutation.SetIDCardFrontURL(v)
	return _c
}

// SetNillableIDCardFrontURL sets the "id_card_front_url" field if the given value is not nil.
func (_c *KycCreate) SetNillableIDCardFrontURL(v *string) *KycCreate {
	if v != nil {
		_c.SetIDCardFrontURL(*v)
	}
	return _c
}

// SetIDCardBackURL sets the "id_card_back_url" field.
func (_c *KycCreate) SetIDCardBackURL(v string) *KycCreate {
	_c.mutation.SetIDCardBackURL(v)
	return _c
}

// SetNillableIDCardBackURL sets the "id_card_back_url" field if the given value is not nil.
func (_c *KycCreate) SetNillableIDCardBackURL(v *string) *KycCreate {
	if v != nil {
		_c.SetIDCardBackURL(*v)
	}
	return _c
}

// SetLicenseFrontURL sets the "license_front_url" field.
func (_c *KycCreate) SetLicenseFrontURL(v string) *KycCreate {
	_c.mutation.SetLicenseFrontURL(v)
	return _c
}

// SetNillableLicenseFrontURL sets the "license_front_url" field if the given value is not nil.
func (_c *KycCreate) SetNillableLicenseFrontURL(v *string) *KycCreate {
	if v != nil {
		_c.SetLicenseFrontURL(*v)
	}
	return _c
}

// SetLicenseBackURL sets the "license_back_url" field.
func (_c *KycCreate) SetLicenseBackURL(v string) *KycCreate {
	_c.mutation.SetLicenseBackURL(v)
	return _c
}

// SetNillableLicenseBackURL sets the "license_back_url" field if the given value is not nil.
func (_c *KycCreate) SetNillableLicenseBackURL(v *string) *KycCreate {
	if v != nil {
		_c.SetLicenseBackURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *KycCreate) SetStatus(v kyc.Status) *KycCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *KycCreate) SetNillableStatus(v *kyc.Status) *KycCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *KycCreate) SetNote(v string) *KycCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *KycCreate) SetNillableNote(v *string) *KycCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *KycCreate) SetReviewedBy(v uuid.UUID) *KycCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *KycCreate) SetNillableReviewedBy(v *uuid.UUID) *KycCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *KycCreate) SetReviewedAt(v time.Time) *KycCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *KycCreate) SetNillableReviewedAt(v *time.Time) *KycCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KycCreate) SetCreatedAt(v time.Time) *KycCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KycCreate) SetNillableCreatedAt(v *time.Time) *KycCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KycCreate) SetUpdatedAt(v time.Time) *KycCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KycCreate) SetNillableUpdatedAt(v *time.Time) *KycCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KycCreate) SetID(v uuid.UUID) *KycCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KycCreate) SetNillableID(v *uuid.UUID) *KycCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the KycMutation object of the builder.
func (_c *KycCreate) Mutation() *KycMutation {
	return _c.mutation
}

// Save creates the Kyc in the database.
func (_c *KycCreate) Save(ctx context.Context) (*Kyc, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KycCreate) SaveX(ctx context.Context) *Kyc {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KycCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KycCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KycCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := kyc.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := kyc.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := kyc.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := kyc.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KycCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Kyc.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Kyc.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := kyc.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Kyc.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Kyc.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Kyc.updated_at"`)}
	}
	return nil
}

func (_c *KycCreate) sqlSave(ctx context.Context) (*Kyc, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KycCreate) createSpec() (*Kyc, *sqlgraph.CreateSpec) {
	var (
		_node = &Kyc{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(kyc.Table, sqlgraph.NewFieldSpec(kyc.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(kyc.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.IDCardNumber(); ok {
		_spec.SetField(kyc.FieldIDCardNumber, field.TypeString, value)
		_node.IDCardNumber = &value
	}
	if value, ok := _c.mutation.LicenseNumber(); ok {
		_spec.SetField(kyc.FieldLicenseNumber, field.TypeString, value)
		_node.LicenseNumber = &value
	}
	if value, ok := _c.mutation.IDCardFrontURL(); ok {
		_spec.SetField(kyc.FieldIDCardFrontURL, field.TypeString, value)
		_node.IDCardFrontURL = value
	}
	if value, ok := _c.mutation.IDCardBackURL(); ok {
		_spec.SetField(kyc.FieldIDCardBackURL, field.TypeString, value)
		_node.IDCardBackURL = value
	}
	if value, ok := _c.mutation.LicenseFrontURL(); ok {
		_spec.SetField(kyc.FieldLicenseFrontURL, field.TypeString, value)
		_node.LicenseFrontURL = value
	}
	if value, ok := _c.mutation.LicenseBackURL(); ok {
		_spec.SetField(kyc.FieldLicenseBackURL, field.TypeString, value)
		_node.LicenseBackURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(kyc.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(kyc.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(kyc.FieldReviewedBy, field.TypeUUID, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(kyc.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(kyc.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(kyc.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// KycCreateBulk is the builder for creating many Kyc entities in bulk.
type KycCreateBulk struct {
	config
	err      error
	builders []*KycCreate
}

// Save creates the Kyc entities in the database.
func (_c *KycCreateBulk) Save(ctx context.Context) ([]*Kyc, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Kyc, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KycMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KycCreateBulk) SaveX(ctx context.Context) []*Kyc {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KycCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KycCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
