// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kyc_service/ent/kyc"
	"kyc_service/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeKyc = "Kyc"
)

// KycMutation represents an operation that mutates the Kyc nodes in the graph.
type KycMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	user_id           *uuid.UUID
	id_card_number    *string
	license_number    *string
	id_card_front_url *string
	id_card_back_url  *string
	license_front_url *string
	license_back_url  *string
	status            *kyc.Status
	note              *string
	reviewed_by       *uuid.UUID
	reviewed_at       *time.Time
	created_at        *time.Time
	updated_at        *time.Time
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Kyc, error)
	predicates        []predicate.Kyc
}

var _ ent.Mutation = (*KycMutation)(nil)

// kycOption allows management of the mutation configuration using functional options.
type kycOption func(*KycMutation)

// newKycMutation creates new mutation for the Kyc entity.
func newKycMutation(c config, op Op, opts ...kycOption) *KycMutation {
	m := &KycMutation{
		config:        c,
		op:            op,
		typ:           TypeKyc,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withKycID sets the ID field of the mutation.
func withKycID(id uuid.UUID) kycOption {
	return func(m *KycMutation) {
		var (
			err   error
			once  sync.Once
			value *Kyc
		)
		m.oldValue = func(ctx context.Context) (*Kyc, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Kyc.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withKyc sets the old Kyc of the mutation.
func withKyc(node *Kyc) kycOption {
	return func(m *KycMutation) {
		m.oldValue = func(context.Context) (*Kyc, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m KycMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m KycMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Kyc entities.
func (m *KycMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *KycMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *KycMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Kyc.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *KycMutation) SetUserID(u uuid.UUID) {
	m.user_id = &u
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *KycMutation) UserID() (r uuid.UUID, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *KycMutation) ResetUserID() {
	m.user_id = nil
}

// SetIDCardNumber sets the "id_card_number" field.
func (m *KycMutation) SetIDCardNumber(s string) {
	m.id_card_number = &s
}

// IDCardNumber returns the value of the "id_card_number" field in the mutation.
func (m *KycMutation) IDCardNumber() (r string, exists bool) {
	v := m.id_card_number
	if v == nil {
		return
	}
	return *v, true
}

// OldIDCardNumber returns the old "id_card_number" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldIDCardNumber(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDCardNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDCardNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDCardNumber: %w", err)
	}
	return oldValue.IDCardNumber, nil
}

// ClearIDCardNumber clears the value of the "id_card_number" field.
func (m *KycMutation) ClearIDCardNumber() {
	m.id_card_number = nil
	m.clearedFields[kyc.FieldIDCardNumber] = struct{}{}
}

// IDCardNumberCleared returns if the "id_card_number" field was cleared in this mutation.
func (m *KycMutation) IDCardNumberCleared() bool {
	_, ok := m.clearedFields[kyc.FieldIDCardNumber]
	return ok
}

// ResetIDCardNumber resets all changes to the "id_card_number" field.
func (m *KycMutation) ResetIDCardNumber() {
	m.id_card_number = nil
	delete(m.clearedFields, kyc.FieldIDCardNumber)
}

// SetLicenseNumber sets the "license_number" field.
func (m *KycMutation) SetLicenseNumber(s string) {
	m.license_number = &s
}

// LicenseNumber returns the value of the "license_number" field in the mutation.
func (m *KycMutation) LicenseNumber() (r string, exists bool) {
	v := m.license_number
	if v == nil {
		return
	}
	return *v, true
}

// OldLicenseNumber returns the old "license_number" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldLicenseNumber(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLicenseNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLicenseNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLicenseNumber: %w", err)
	}
	return oldValue.LicenseNumber, nil
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (m *KycMutation) ClearLicenseNumber() {
	m.license_number = nil
	m.clearedFields[kyc.FieldLicenseNumber] = struct{}{}
}

// LicenseNumberCleared returns if the "license_number" field was cleared in this mutation.
func (m *KycMutation) LicenseNumberCleared() bool {
	_, ok := m.clearedFields[kyc.FieldLicenseNumber]
	return ok
}

// ResetLicenseNumber resets all changes to the "license_number" field.
func (m *KycMutation) ResetLicenseNumber() {
	m.license_number = nil
	delete(m.clearedFields, kyc.FieldLicenseNumber)
}

// SetIDCardFrontURL sets the "id_card_front_url" field.
func (m *KycMutation) SetIDCardFrontURL(s string) {
	m.id_card_front_url = &s
}

// IDCardFrontURL returns the value of the "id_card_front_url" field in the mutation.
func (m *KycMutation) IDCardFrontURL() (r string, exists bool) {
	v := m.id_card_front_url
	if v == nil {
		return
	}
	return *v, true
}

// OldIDCardFrontURL returns the old "id_card_front_url" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldIDCardFrontURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDCardFrontURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDCardFrontURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDCardFrontURL: %w", err)
	}
	return oldValue.IDCardFrontURL, nil
}

// ClearIDCardFrontURL clears the value of the "id_card_front_url" field.
func (m *KycMutation) ClearIDCardFrontURL() {
	m.id_card_front_url = nil
	m.clearedFields[kyc.FieldIDCardFrontURL] = struct{}{}
}

// IDCardFrontURLCleared returns if the "id_card_front_url" field was cleared in this mutation.
func (m *KycMutation) IDCardFrontURLCleared() bool {
	_, ok := m.clearedFields[kyc.FieldIDCardFrontURL]
	return ok
}

// ResetIDCardFrontURL resets all changes to the "id_card_front_url" field.
func (m *KycMutation) ResetIDCardFrontURL() {
	m.id_card_front_url = nil
	delete(m.clearedFields, kyc.FieldIDCardFrontURL)
}

// SetIDCardBackURL sets the "id_card_back_url" field.
func (m *KycMutation) SetIDCardBackURL(s string) {
	m.id_card_back_url = &s
}

// IDCardBackURL returns the value of the "id_card_back_url" field in the mutation.
func (m *KycMutation) IDCardBackURL() (r string, exists bool) {
	v := m.id_card_back_url
	if v == nil {
		return
	}
	return *v, true
}

// OldIDCardBackURL returns the old "id_card_back_url" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldIDCardBackURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDCardBackURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDCardBackURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDCardBackURL: %w", err)
	}
	return oldValue.IDCardBackURL, nil
}

// ClearIDCardBackURL clears the value of the "id_card_back_url" field.
func (m *KycMutation) ClearIDCardBackURL() {
	m.id_card_back_url = nil
	m.clearedFields[kyc.FieldIDCardBackURL] = struct{}{}
}

// IDCardBackURLCleared returns if the "id_card_back_url" field was cleared in this mutation.
func (m *KycMutation) IDCardBackURLCleared() bool {
	_, ok := m.clearedFields[kyc.FieldIDCardBackURL]
	return ok
}

// ResetIDCardBackURL resets all changes to the "id_card_back_url" field.
func (m *KycMutation) ResetIDCardBackURL() {
	m.id_card_back_url = nil
	delete(m.clearedFields, kyc.FieldIDCardBackURL)
}

// SetLicenseFrontURL sets the "license_front_url" field.
func (m *KycMutation) SetLicenseFrontURL(s string) {
	m.license_front_url = &s
}

// LicenseFrontURL returns the value of the "license_front_url" field in the mutation.
func (m *KycMutation) LicenseFrontURL() (r string, exists bool) {
	v := m.license_front_url
	if v == nil {
		return
	}
	return *v, true
}

// OldLicenseFrontURL returns the old "license_front_url" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldLicenseFrontURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLicenseFrontURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLicenseFrontURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLicenseFrontURL: %w", err)
	}
	return oldValue.LicenseFrontURL, nil
}

// ClearLicenseFrontURL clears the value of the "license_front_url" field.
func (m *KycMutation) ClearLicenseFrontURL() {
	m.license_front_url = nil
	m.clearedFields[kyc.FieldLicenseFrontURL] = struct{}{}
}

// LicenseFrontURLCleared returns if the "license_front_url" field was cleared in this mutation.
func (m *KycMutation) LicenseFrontURLCleared() bool {
	_, ok := m.clearedFields[kyc.FieldLicenseFrontURL]
	return ok
}

// ResetLicenseFrontURL resets all changes to the "license_front_url" field.
func (m *KycMutation) ResetLicenseFrontURL() {
	m.license_front_url = nil
	delete(m.clearedFields, kyc.FieldLicenseFrontURL)
}

// SetLicenseBackURL sets the "license_back_url" field.
func (m *KycMutation) SetLicenseBackURL(s string) {
	m.license_back_url = &s
}

// LicenseBackURL returns the value of the "license_back_url" field in the mutation.
func (m *KycMutation) LicenseBackURL() (r string, exists bool) {
	v := m.license_back_url
	if v == nil {
		return
	}
	return *v, true
}

// OldLicenseBackURL returns the old "license_back_url" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldLicenseBackURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLicenseBackURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLicenseBackURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLicenseBackURL: %w", err)
	}
	return oldValue.LicenseBackURL, nil
}

// ClearLicenseBackURL clears the value of the "license_back_url" field.
func (m *KycMutation) ClearLicenseBackURL() {
	m.license_back_url = nil
	m.clearedFields[kyc.FieldLicenseBackURL] = struct{}{}
}

// LicenseBackURLCleared returns if the "license_back_url" field was cleared in this mutation.
func (m *KycMutation) LicenseBackURLCleared() bool {
	_, ok := m.clearedFields[kyc.FieldLicenseBackURL]
	return ok
}

// ResetLicenseBackURL resets all changes to the "license_back_url" field.
func (m *KycMutation) ResetLicenseBackURL() {
	m.license_back_url = nil
	delete(m.clearedFields, kyc.FieldLicenseBackURL)
}

// SetStatus sets the "status" field.
func (m *KycMutation) SetStatus(k kyc.Status) {
	m.status = &k
}

// Status returns the value of the "status" field in the mutation.
func (m *KycMutation) Status() (r kyc.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldStatus(ctx context.Context) (v kyc.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *KycMutation) ResetStatus() {
	m.status = nil
}

// SetNote sets the "note" field.
func (m *KycMutation) SetNote(s string) {
	m.note = &s
}

// Note returns the value of the "note" field in the mutation.
func (m *KycMutation) Note() (r string, exists bool) {
	v := m.note
	if v == nil {
		return
	}
	return *v, true
}

// OldNote returns the old "note" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldNote(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNote is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNote requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNote: %w", err)
	}
	return oldValue.Note, nil
}

// ClearNote clears the value of the "note" field.
func (m *KycMutation) ClearNote() {
	m.note = nil
	m.clearedFields[kyc.FieldNote] = struct{}{}
}

// NoteCleared returns if the "note" field was cleared in this mutation.
func (m *KycMutation) NoteCleared() bool {
	_, ok := m.clearedFields[kyc.FieldNote]
	return ok
}

// ResetNote resets all changes to the "note" field.
func (m *KycMutation) ResetNote() {
	m.note = nil
	delete(m.clearedFields, kyc.FieldNote)
}

// SetReviewedBy sets the "reviewed_by" field.
func (m *KycMutation) SetReviewedBy(u uuid.UUID) {
	m.reviewed_by = &u
}

// ReviewedBy returns the value of the "reviewed_by" field in the mutation.
func (m *KycMutation) ReviewedBy() (r uuid.UUID, exists bool) {
	v := m.reviewed_by
	if v == nil {
		return
	}
	return *v, true
}

// OldReviewedBy returns the old "reviewed_by" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldReviewedBy(ctx context.Context) (v *uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReviewedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReviewedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReviewedBy: %w", err)
	}
	return oldValue.ReviewedBy, nil
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (m *KycMutation) ClearReviewedBy() {
	m.reviewed_by = nil
	m.clearedFields[kyc.FieldReviewedBy] = struct{}{}
}

// ReviewedByCleared returns if the "reviewed_by" field was cleared in this mutation.
func (m *KycMutation) ReviewedByCleared() bool {
	_, ok := m.clearedFields[kyc.FieldReviewedBy]
	return ok
}

// ResetReviewedBy resets all changes to the "reviewed_by" field.
func (m *KycMutation) ResetReviewedBy() {
	m.reviewed_by = nil
	delete(m.clearedFields, kyc.FieldReviewedBy)
}

// SetReviewedAt sets the "reviewed_at" field.
func (m *KycMutation) SetReviewedAt(t time.Time) {
	m.reviewed_at = &t
}

// ReviewedAt returns the value of the "reviewed_at" field in the mutation.
func (m *KycMutation) ReviewedAt() (r time.Time, exists bool) {
	v := m.reviewed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldReviewedAt returns the old "reviewed_at" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldReviewedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReviewedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReviewedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReviewedAt: %w", err)
	}
	return oldValue.ReviewedAt, nil
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (m *KycMutation) ClearReviewedAt() {
	m.reviewed_at = nil
	m.clearedFields[kyc.FieldReviewedAt] = struct{}{}
}

// ReviewedAtCleared returns if the "reviewed_at" field was cleared in this mutation.
func (m *KycMutation) ReviewedAtCleared() bool {
	_, ok := m.clearedFields[kyc.FieldReviewedAt]
	return ok
}

// ResetReviewedAt resets all changes to the "reviewed_at" field.
func (m *KycMutation) ResetReviewedAt() {
	m.reviewed_at = nil
	delete(m.clearedFields, kyc.FieldReviewedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *KycMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *KycMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *KycMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *KycMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *KycMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Kyc entity.
// If the Kyc object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KycMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *KycMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the KycMutation builder.
func (m *KycMutation) Where(ps ...predicate.Kyc) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the KycMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *KycMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Kyc, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *KycMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *KycMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Kyc).
func (m *KycMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *KycMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.user_id != nil {
		fields = append(fields, kyc.FieldUserID)
	}
	if m.id_card_number != nil {
		fields = append(fields, kyc.FieldIDCardNumber)
	}
	if m.license_number != nil {
		fields = append(fields, kyc.FieldLicenseNumber)
	}
	if m.id_card_front_url != nil {
		fields = append(fields, kyc.FieldIDCardFrontURL)
	}
	if m.id_card_back_url != nil {
		fields = append(fields, kyc.FieldIDCardBackURL)
	}
	if m.license_front_url != nil {
		fields = append(fields, kyc.FieldLicenseFrontURL)
	}
	if m.license_back_url != nil {
		fields = append(fields, kyc.FieldLicenseBackURL)
	}
	if m.status != nil {
		fields = append(fields, kyc.FieldStatus)
	}
	if m.note != nil {
		fields = append(fields, kyc.FieldNote)
	}
	if m.reviewed_by != nil {
		fields = append(fields, kyc.FieldReviewedBy)
	}
	if m.reviewed_at != nil {
		fields = append(fields, kyc.FieldReviewedAt)
	}
	if m.created_at != nil {
		fields = append(fields, kyc.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, kyc.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *KycMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case kyc.FieldUserID:
		return m.UserID()
	case kyc.FieldIDCardNumber:
		return m.IDCardNumber()
	case kyc.FieldLicenseNumber:
		return m.LicenseNumber()
	case kyc.FieldIDCardFrontURL:
		return m.IDCardFrontURL()
	case kyc.FieldIDCardBackURL:
		return m.IDCardBackURL()
	case kyc.FieldLicenseFrontURL:
		return m.LicenseFrontURL()
	case kyc.FieldLicenseBackURL:
		return m.LicenseBackURL()
	case kyc.FieldStatus:
		return m.Status()
	case kyc.FieldNote:
		return m.Note()
	case kyc.FieldReviewedBy:
		return m.ReviewedBy()
	case kyc.FieldReviewedAt:
		return m.ReviewedAt()
	case kyc.FieldCreatedAt:
		return m.CreatedAt()
	case kyc.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *KycMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case kyc.FieldUserID:
		return m.OldUserID(ctx)
	case kyc.FieldIDCardNumber:
		return m.OldIDCardNumber(ctx)
	case kyc.FieldLicenseNumber:
		return m.OldLicenseNumber(ctx)
	case kyc.FieldIDCardFrontURL:
		return m.OldIDCardFrontURL(ctx)
	case kyc.FieldIDCardBackURL:
		return m.OldIDCardBackURL(ctx)
	case kyc.FieldLicenseFrontURL:
		return m.OldLicenseFrontURL(ctx)
	case kyc.FieldLicenseBackURL:
		return m.OldLicenseBackURL(ctx)
	case kyc.FieldStatus:
		return m.OldStatus(ctx)
	case kyc.FieldNote:
		return m.OldNote(ctx)
	case kyc.FieldReviewedBy:
		return m.OldReviewedBy(ctx)
	case kyc.FieldReviewedAt:
		return m.OldReviewedAt(ctx)
	case kyc.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case kyc.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Kyc field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *KycMutation) SetField(name string, value ent.Value) error {
	switch name {
	case kyc.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case kyc.FieldIDCardNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDCardNumber(v)
		return nil
	case kyc.FieldLicenseNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLicenseNumber(v)
		return nil
	case kyc.FieldIDCardFrontURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDCardFrontURL(v)
		return nil
	case kyc.FieldIDCardBackURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDCardBackURL(v)
		return nil
	case kyc.FieldLicenseFrontURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLicenseFrontURL(v)
		return nil
	case kyc.FieldLicenseBackURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLicenseBackURL(v)
		return nil
	case kyc.FieldStatus:
		v, ok := value.(kyc.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case kyc.FieldNote:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNote(v)
		return nil
	case kyc.FieldReviewedBy:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReviewedBy(v)
		return nil
	case kyc.FieldReviewedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReviewedAt(v)
		return nil
	case kyc.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case kyc.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Kyc field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *KycMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *KycMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *KycMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Kyc numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *KycMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(kyc.FieldIDCardNumber) {
		fields = append(fields, kyc.FieldIDCardNumber)
	}
	if m.FieldCleared(kyc.FieldLicenseNumber) {
		fields = append(fields, kyc.FieldLicenseNumber)
	}
	if m.FieldCleared(kyc.FieldIDCardFrontURL) {
		fields = append(fields, kyc.FieldIDCardFrontURL)
	}
	if m.FieldCleared(kyc.FieldIDCardBackURL) {
		fields = append(fields, kyc.FieldIDCardBackURL)
	}
	if m.FieldCleared(kyc.FieldLicenseFrontURL) {
		fields = append(fields, kyc.FieldLicenseFrontURL)
	}
	if m.FieldCleared(kyc.FieldLicenseBackURL) {
		fields = append(fields, kyc.FieldLicenseBackURL)
	}
	if m.FieldCleared(kyc.FieldNote) {
		fields = append(fields, kyc.FieldNote)
	}
	if m.FieldCleared(kyc.FieldReviewedBy) {
		fields = append(fields, kyc.FieldReviewedBy)
	}
	if m.FieldCleared(kyc.FieldReviewedAt) {
		fields = append(fields, kyc.FieldReviewedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *KycMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *KycMutation) ClearField(name string) error {
	switch name {
	case kyc.FieldIDCardNumber:
		m.ClearIDCardNumber()
		return nil
	case kyc.FieldLicenseNumber:
		m.ClearLicenseNumber()
		return nil
	case kyc.FieldIDCardFrontURL:
		m.ClearIDCardFrontURL()
		return nil
	case kyc.FieldIDCardBackURL:
		m.ClearIDCardBackURL()
		return nil
	case kyc.FieldLicenseFrontURL:
		m.ClearLicenseFrontURL()
		return nil
	case kyc.FieldLicenseBackURL:
		m.ClearLicenseBackURL()
		return nil
	case kyc.FieldNote:
		m.ClearNote()
		return nil
	case kyc.FieldReviewedBy:
		m.ClearReviewedBy()
		return nil
	case kyc.FieldReviewedAt:
		m.ClearReviewedAt()
		return nil
	}
	return fmt.Errorf("unknown Kyc nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *KycMutation) ResetField(name string) error {
	switch name {
	case kyc.FieldUserID:
		m.ResetUserID()
		return nil
	case kyc.FieldIDCardNumber:
		m.ResetIDCardNumber()
		return nil
	case kyc.FieldLicenseNumber:
		m.ResetLicenseNumber()
		return nil
	case kyc.FieldIDCardFrontURL:
		m.ResetIDCardFrontURL()
		return nil
	case kyc.FieldIDCardBackURL:
		m.ResetIDCardBackURL()
		return nil
	case kyc.FieldLicenseFrontURL:
		m.ResetLicenseFrontURL()
		return nil
	case kyc.FieldLicenseBackURL:
		m.ResetLicenseBackURL()
		return nil
	case kyc.FieldStatus:
		m.ResetStatus()
		return nil
	case kyc.FieldNote:
		m.ResetNote()
		return nil
	case kyc.FieldReviewedBy:
		m.ResetReviewedBy()
		return nil
	case kyc.FieldReviewedAt:
		m.ResetReviewedAt()
		return nil
	case kyc.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case kyc.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Kyc field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *KycMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *KycMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *KycMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *KycMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *KycMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *KycMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *KycMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Kyc unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *KycMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Kyc edge %s", name)
}
