// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kyc_service/ent/kyc"
	"kyc_service/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	kycFields := schema.Kyc{}.Fields()
	_ = kycFields
	// kycDescCreatedAt is the schema descriptor for created_at field.
	kycDescCreatedAt := kycFields[12].Descriptor()
	// kyc.DefaultCreatedAt holds the default value on creation for the created_at field.
	kyc.DefaultCreatedAt = kycDescCreatedAt.Default.(func() time.Time)
	// kycDescUpdatedAt is the schema descriptor for updated_at field.
	kycDescUpdatedAt := kycFields[13].Descriptor()
	// kyc.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	kyc.DefaultUpdatedAt = kycDescUpdatedAt.Default.(func() time.Time)
	// kyc.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	kyc.UpdateDefaultUpdatedAt = kycDescUpdatedAt.UpdateDefault.(func() time.Time)
	// kycDescID is the schema descriptor for id field.
	kycDescID := kycFields[0].Descriptor()
	// kyc.DefaultID holds the default value on creation for the id field.
	kyc.DefaultID = kycDescID.Default.(func() uuid.UUID)
}
