// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KycsColumns holds the columns for the "kycs" table.
	KycsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
		{Name: "id_card_number", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "license_number", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "id_card_front_url", Type: field.TypeString, Nullable: true},
		{Name: "id_card_back_url", Type: field.TypeString, Nullable: true},
		{Name: "license_front_url", Type: field.TypeString, Nullable: true},
		{Name: "license_back_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "rejected"}, Default: "pending"},
		{Name: "note", Type: field.TypeString, Nullable: true},
		{Name: "reviewed_by", Type: field.TypeUUID, Nullable: true},
		{Name: "reviewed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KycsTable holds the schema information for the "kycs" table.
	KycsTable = &schema.Table{
		Name:       "kycs",
		Columns:    KycsColumns,
		PrimaryKey: []*schema.Column{KycsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "kyc_status",
				Unique:  false,
				Columns: []*schema.Column{KycsColumns[8]},
			},
			{
				Name:    "kyc_user_id",
				Unique:  true,
				Columns: []*schema.Column{KycsColumns[1]},
			},
			{
				Name:    "kyc_created_at",
				Unique:  false,
				Columns: []*schema.Column{KycsColumns[12]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KycsTable,
	}
)

func init() {
}
