// Code generated by ent, DO NOT EDIT.

package kyc

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the kyc type in the database.
	Label = "kyc"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldIDCardNumber holds the string denoting the id_card_number field in the database.
	FieldIDCardNumber = "id_card_number"
	// FieldLicenseNumber holds the string denoting the license_number field in the database.
	FieldLicenseNumber = "license_number"
	// FieldIDCardFrontURL holds the string denoting the id_card_front_url field in the database.
	FieldIDCardFrontURL = "id_card_front_url"
	// FieldIDCardBackURL holds the string denoting the id_card_back_url field in the database.
	FieldIDCardBackURL = "id_card_back_url"
	// FieldLicenseFrontURL holds the string denoting the license_front_url field in the database.
	FieldLicenseFrontURL = "license_front_url"
	// FieldLicenseBackURL holds the string denoting the license_back_url field in the database.
	FieldLicenseBackURL = "license_back_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldReviewedBy holds the string denoting the reviewed_by field in the database.
	FieldReviewedBy = "reviewed_by"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the kyc in the database.
	Table = "kycs"
)

// Columns holds all SQL columns for kyc fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldIDCardNumber,
	FieldLicenseNumber,
	FieldIDCardFrontURL,
	FieldIDCardBackURL,
	FieldLicenseFrontURL,
	FieldLicenseBackURL,
	FieldStatus,
	FieldNote,
	FieldReviewedBy,
	FieldReviewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusRejected Status = "rejected"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusApproved, StatusRejected:
		return nil
	default:
		return fmt.Errorf("kyc: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Kyc queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByIDCardNumber orders the results by the id_card_number field.
func ByIDCardNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDCardNumber, opts...).ToFunc()
}

// ByLicenseNumber orders the results by the license_number field.
func ByLicenseNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseNumber, opts...).ToFunc()
}

// ByIDCardFrontURL orders the results by the id_card_front_url field.
func ByIDCardFrontURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDCardFrontURL, opts...).ToFunc()
}

// ByIDCardBackURL orders the results by the id_card_back_url field.
func ByIDCardBackURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDCardBackURL, opts...).ToFunc()
}

// ByLicenseFrontURL orders the results by the license_front_url field.
func ByLicenseFrontURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseFrontURL, opts...).ToFunc()
}

// ByLicenseBackURL orders the results by the license_back_url field.
func ByLicenseBackURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseBackURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByReviewedBy orders the results by the reviewed_by field.
func ByReviewedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedBy, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
