// Code generated by ent, DO NOT EDIT.

package kyc

import (
	"kyc_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldUserID, v))
}

// IDCardNumber applies equality check predicate on the "id_card_number" field. It's identical to IDCardNumberEQ.
func IDCardNumber(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardNumber, v))
}

// LicenseNumber applies equality check predicate on the "license_number" field. It's identical to LicenseNumberEQ.
func LicenseNumber(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseNumber, v))
}

// IDCardFrontURL applies equality check predicate on the "id_card_front_url" field. It's identical to IDCardFrontURLEQ.
func IDCardFrontURL(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardFrontURL, v))
}

// IDCardBackURL applies equality check predicate on the "id_card_back_url" field. It's identical to IDCardBackURLEQ.
func IDCardBackURL(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardBackURL, v))
}

// LicenseFrontURL applies equality check predicate on the "license_front_url" field. It's identical to LicenseFrontURLEQ.
func LicenseFrontURL(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseFrontURL, v))
}

// LicenseBackURL applies equality check predicate on the "license_back_url" field. It's identical to LicenseBackURLEQ.
func LicenseBackURL(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseBackURL, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldNote, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldUserID, v))
}

// IDCardNumberEQ applies the EQ predicate on the "id_card_number" field.
func IDCardNumberEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardNumber, v))
}

// IDCardNumberNEQ applies the NEQ predicate on the "id_card_number" field.
func IDCardNumberNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldIDCardNumber, v))
}

// IDCardNumberIn applies the In predicate on the "id_card_number" field.
func IDCardNumberIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldIDCardNumber, vs...))
}

// IDCardNumberNotIn applies the NotIn predicate on the "id_card_number" field.
func IDCardNumberNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldIDCardNumber, vs...))
}

// IDCardNumberGT applies the GT predicate on the "id_card_number" field.
func IDCardNumberGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldIDCardNumber, v))
}

// IDCardNumberGTE applies the GTE predicate on the "id_card_number" field.
func IDCardNumberGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldIDCardNumber, v))
}

// IDCardNumberLT applies the LT predicate on the "id_card_number" field.
func IDCardNumberLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldIDCardNumber, v))
}

// IDCardNumberLTE applies the LTE predicate on the "id_card_number" field.
func IDCardNumberLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldIDCardNumber, v))
}

// IDCardNumberContains applies the Contains predicate on the "id_card_number" field.
func IDCardNumberContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldIDCardNumber, v))
}

// IDCardNumberHasPrefix applies the HasPrefix predicate on the "id_card_number" field.
func IDCardNumberHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldIDCardNumber, v))
}

// IDCardNumberHasSuffix applies the HasSuffix predicate on the "id_card_number" field.
func IDCardNumberHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldIDCardNumber, v))
}

// IDCardNumberIsNil applies the IsNil predicate on the "id_card_number" field.
func IDCardNumberIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldIDCardNumber))
}

// IDCardNumberNotNil applies the NotNil predicate on the "id_card_number" field.
func IDCardNumberNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldIDCardNumber))
}

// IDCardNumberEqualFold applies the EqualFold predicate on the "id_card_number" field.
func IDCardNumberEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldIDCardNumber, v))
}

// IDCardNumberContainsFold applies the ContainsFold predicate on the "id_card_number" field.
func IDCardNumberContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldIDCardNumber, v))
}

// LicenseNumberEQ applies the EQ predicate on the "license_number" field.
func LicenseNumberEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseNumber, v))
}

// LicenseNumberNEQ applies the NEQ predicate on the "license_number" field.
func LicenseNumberNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldLicenseNumber, v))
}

// LicenseNumberIn applies the In predicate on the "license_number" field.
func LicenseNumberIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldLicenseNumber, vs...))
}

// LicenseNumberNotIn applies the NotIn predicate on the "license_number" field.
func LicenseNumberNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldLicenseNumber, vs...))
}

// LicenseNumberGT applies the GT predicate on the "license_number" field.
func LicenseNumberGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldLicenseNumber, v))
}

// LicenseNumberGTE applies the GTE predicate on the "license_number" field.
func LicenseNumberGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldLicenseNumber, v))
}

// LicenseNumberLT applies the LT predicate on the "license_number" field.
func LicenseNumberLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldLicenseNumber, v))
}

// LicenseNumberLTE applies the LTE predicate on the "license_number" field.
func LicenseNumberLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldLicenseNumber, v))
}

// LicenseNumberContains applies the Contains predicate on the "license_number" field.
func LicenseNumberContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldLicenseNumber, v))
}

// LicenseNumberHasPrefix applies the HasPrefix predicate on the "license_number" field.
func LicenseNumberHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldLicenseNumber, v))
}

// LicenseNumberHasSuffix applies the HasSuffix predicate on the "license_number" field.
func LicenseNumberHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldLicenseNumber, v))
}

// LicenseNumberIsNil applies the IsNil predicate on the "license_number" field.
func LicenseNumberIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldLicenseNumber))
}

// LicenseNumberNotNil applies the NotNil predicate on the "license_number" field.
func LicenseNumberNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldLicenseNumber))
}

// LicenseNumberEqualFold applies the EqualFold predicate on the "license_number" field.
func LicenseNumberEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldLicenseNumber, v))
}

// LicenseNumberContainsFold applies the ContainsFold predicate on the "license_number" field.
func LicenseNumberContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldLicenseNumber, v))
}

// IDCardFrontURLEQ applies the EQ predicate on the "id_card_front_url" field.
func IDCardFrontURLEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardFrontURL, v))
}

// IDCardFrontURLNEQ applies the NEQ predicate on the "id_card_front_url" field.
func IDCardFrontURLNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldIDCardFrontURL, v))
}

// IDCardFrontURLIn applies the In predicate on the "id_card_front_url" field.
func IDCardFrontURLIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldIDCardFrontURL, vs...))
}

// IDCardFrontURLNotIn applies the NotIn predicate on the "id_card_front_url" field.
func IDCardFrontURLNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldIDCardFrontURL, vs...))
}

// IDCardFrontURLGT applies the GT predicate on the "id_card_front_url" field.
func IDCardFrontURLGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldIDCardFrontURL, v))
}

// IDCardFrontURLGTE applies the GTE predicate on the "id_card_front_url" field.
func IDCardFrontURLGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldIDCardFrontURL, v))
}

// IDCardFrontURLLT applies the LT predicate on the "id_card_front_url" field.
func IDCardFrontURLLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldIDCardFrontURL, v))
}

// IDCardFrontURLLTE applies the LTE predicate on the "id_card_front_url" field.
func IDCardFrontURLLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldIDCardFrontURL, v))
}

// IDCardFrontURLContains applies the Contains predicate on the "id_card_front_url" field.
func IDCardFrontURLContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldIDCardFrontURL, v))
}

// IDCardFrontURLHasPrefix applies the HasPrefix predicate on the "id_card_front_url" field.
func IDCardFrontURLHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldIDCardFrontURL, v))
}

// IDCardFrontURLHasSuffix applies the HasSuffix predicate on the "id_card_front_url" field.
func IDCardFrontURLHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldIDCardFrontURL, v))
}

// IDCardFrontURLIsNil applies the IsNil predicate on the "id_card_front_url" field.
func IDCardFrontURLIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldIDCardFrontURL))
}

// IDCardFrontURLNotNil applies the NotNil predicate on the "id_card_front_url" field.
func IDCardFrontURLNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldIDCardFrontURL))
}

// IDCardFrontURLEqualFold applies the EqualFold predicate on the "id_card_front_url" field.
func IDCardFrontURLEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldIDCardFrontURL, v))
}

// IDCardFrontURLContainsFold applies the ContainsFold predicate on the "id_card_front_url" field.
func IDCardFrontURLContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldIDCardFrontURL, v))
}

// IDCardBackURLEQ applies the EQ predicate on the "id_card_back_url" field.
func IDCardBackURLEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldIDCardBackURL, v))
}

// IDCardBackURLNEQ applies the NEQ predicate on the "id_card_back_url" field.
func IDCardBackURLNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldIDCardBackURL, v))
}

// IDCardBackURLIn applies the In predicate on the "id_card_back_url" field.
func IDCardBackURLIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldIDCardBackURL, vs...))
}

// IDCardBackURLNotIn applies the NotIn predicate on the "id_card_back_url" field.
func IDCardBackURLNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldIDCardBackURL, vs...))
}

// IDCardBackURLGT applies the GT predicate on the "id_card_back_url" field.
func IDCardBackURLGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldIDCardBackURL, v))
}

// IDCardBackURLGTE applies the GTE predicate on the "id_card_back_url" field.
func IDCardBackURLGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldIDCardBackURL, v))
}

// IDCardBackURLLT applies the LT predicate on the "id_card_back_url" field.
func IDCardBackURLLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldIDCardBackURL, v))
}

// IDCardBackURLLTE applies the LTE predicate on the "id_card_back_url" field.
func IDCardBackURLLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldIDCardBackURL, v))
}

// IDCardBackURLContains applies the Contains predicate on the "id_card_back_url" field.
func IDCardBackURLContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldIDCardBackURL, v))
}

// IDCardBackURLHasPrefix applies the HasPrefix predicate on the "id_card_back_url" field.
func IDCardBackURLHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldIDCardBackURL, v))
}

// IDCardBackURLHasSuffix applies the HasSuffix predicate on the "id_card_back_url" field.
func IDCardBackURLHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldIDCardBackURL, v))
}

// IDCardBackURLIsNil applies the IsNil predicate on the "id_card_back_url" field.
func IDCardBackURLIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldIDCardBackURL))
}

// IDCardBackURLNotNil applies the NotNil predicate on the "id_card_back_url" field.
func IDCardBackURLNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldIDCardBackURL))
}

// IDCardBackURLEqualFold applies the EqualFold predicate on the "id_card_back_url" field.
func IDCardBackURLEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldIDCardBackURL, v))
}

// IDCardBackURLContainsFold applies the ContainsFold predicate on the "id_card_back_url" field.
func IDCardBackURLContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldIDCardBackURL, v))
}

// LicenseFrontURLEQ applies the EQ predicate on the "license_front_url" field.
func LicenseFrontURLEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseFrontURL, v))
}

// LicenseFrontURLNEQ applies the NEQ predicate on the "license_front_url" field.
func LicenseFrontURLNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldLicenseFrontURL, v))
}

// LicenseFrontURLIn applies the In predicate on the "license_front_url" field.
func LicenseFrontURLIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldLicenseFrontURL, vs...))
}

// LicenseFrontURLNotIn applies the NotIn predicate on the "license_front_url" field.
func LicenseFrontURLNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldLicenseFrontURL, vs...))
}

// LicenseFrontURLGT applies the GT predicate on the "license_front_url" field.
func LicenseFrontURLGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldLicenseFrontURL, v))
}

// LicenseFrontURLGTE applies the GTE predicate on the "license_front_url" field.
func LicenseFrontURLGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldLicenseFrontURL, v))
}

// LicenseFrontURLLT applies the LT predicate on the "license_front_url" field.
func LicenseFrontURLLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldLicenseFrontURL, v))
}

// LicenseFrontURLLTE applies the LTE predicate on the "license_front_url" field.
func LicenseFrontURLLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldLicenseFrontURL, v))
}

// LicenseFrontURLContains applies the Contains predicate on the "license_front_url" field.
func LicenseFrontURLContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldLicenseFrontURL, v))
}

// LicenseFrontURLHasPrefix applies the HasPrefix predicate on the "license_front_url" field.
func LicenseFrontURLHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldLicenseFrontURL, v))
}

// LicenseFrontURLHasSuffix applies the HasSuffix predicate on the "license_front_url" field.
func LicenseFrontURLHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldLicenseFrontURL, v))
}

// LicenseFrontURLIsNil applies the IsNil predicate on the "license_front_url" field.
func LicenseFrontURLIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldLicenseFrontURL))
}

// LicenseFrontURLNotNil applies the NotNil predicate on the "license_front_url" field.
func LicenseFrontURLNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldLicenseFrontURL))
}

// LicenseFrontURLEqualFold applies the EqualFold predicate on the "license_front_url" field.
func LicenseFrontURLEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldLicenseFrontURL, v))
}

// LicenseFrontURLContainsFold applies the ContainsFold predicate on the "license_front_url" field.
func LicenseFrontURLContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldLicenseFrontURL, v))
}

// LicenseBackURLEQ applies the EQ predicate on the "license_back_url" field.
func LicenseBackURLEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldLicenseBackURL, v))
}

// LicenseBackURLNEQ applies the NEQ predicate on the "license_back_url" field.
func LicenseBackURLNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldLicenseBackURL, v))
}

// LicenseBackURLIn applies the In predicate on the "license_back_url" field.
func LicenseBackURLIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldLicenseBackURL, vs...))
}

// LicenseBackURLNotIn applies the NotIn predicate on the "license_back_url" field.
func LicenseBackURLNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldLicenseBackURL, vs...))
}

// LicenseBackURLGT applies the GT predicate on the "license_back_url" field.
func LicenseBackURLGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldLicenseBackURL, v))
}

// LicenseBackURLGTE applies the GTE predicate on the "license_back_url" field.
func LicenseBackURLGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldLicenseBackURL, v))
}

// LicenseBackURLLT applies the LT predicate on the "license_back_url" field.
func LicenseBackURLLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldLicenseBackURL, v))
}

// LicenseBackURLLTE applies the LTE predicate on the "license_back_url" field.
func LicenseBackURLLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldLicenseBackURL, v))
}

// LicenseBackURLContains applies the Contains predicate on the "license_back_url" field.
func LicenseBackURLContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldLicenseBackURL, v))
}

// LicenseBackURLHasPrefix applies the HasPrefix predicate on the "license_back_url" field.
func LicenseBackURLHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldLicenseBackURL, v))
}

// LicenseBackURLHasSuffix applies the HasSuffix predicate on the "license_back_url" field.
func LicenseBackURLHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldLicenseBackURL, v))
}

// LicenseBackURLIsNil applies the IsNil predicate on the "license_back_url" field.
func LicenseBackURLIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldLicenseBackURL))
}

// LicenseBackURLNotNil applies the NotNil predicate on the "license_back_url" field.
func LicenseBackURLNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldLicenseBackURL))
}

// LicenseBackURLEqualFold applies the EqualFold predicate on the "license_back_url" field.
func LicenseBackURLEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldLicenseBackURL, v))
}

// LicenseBackURLContainsFold applies the ContainsFold predicate on the "license_back_url" field.
func LicenseBackURLContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldLicenseBackURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldStatus, vs...))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Kyc {
	return predicate.Kyc(sql.FieldContainsFold(FieldNote, v))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v uuid.UUID) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.Kyc {
	return predicate.Kyc(sql.FieldNotNull(FieldReviewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Kyc {
	return predicate.Kyc(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Kyc) predicate.Kyc {
	return predicate.Kyc(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Kyc) predicate.Kyc {
	return predicate.Kyc(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Kyc) predicate.Kyc {
	return predicate.Kyc(sql.NotPredicates(p))
}
