// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logistic/kyc_service/v1/kyc_messages.proto

package kycv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KycDocument struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdCardNumber    string                 `protobuf:"bytes,3,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	LicenseNumber   string                 `protobuf:"bytes,4,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	IdCardFrontUrl  string                 `protobuf:"bytes,5,opt,name=id_card_front_url,json=idCardFrontUrl,proto3" json:"id_card_front_url,omitempty"`
	IdCardBackUrl   string                 `protobuf:"bytes,6,opt,name=id_card_back_url,json=idCardBackUrl,proto3" json:"id_card_back_url,omitempty"`
	LicenseFrontUrl string                 `protobuf:"bytes,7,opt,name=license_front_url,json=licenseFrontUrl,proto3" json:"license_front_url,omitempty"`
	LicenseBackUrl  string                 `protobuf:"bytes,8,opt,name=license_back_url,json=licenseBackUrl,proto3" json:"license_back_url,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // pending, approved, rejected
	Note            string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	ReviewerId      []byte                 `protobuf:"bytes,11,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	ReviewedAt      string                 `protobuf:"bytes,12,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KycDocument) Reset() {
	*x = KycDocument{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycDocument) ProtoMessage() {}

func (x *KycDocument) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycDocument.ProtoReflect.Descriptor instead.
func (*KycDocument) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{0}
}

func (x *KycDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KycDocument) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *KycDocument) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *KycDocument) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *KycDocument) GetIdCardFrontUrl() string {
	if x != nil {
		return x.IdCardFrontUrl
	}
	return ""
}

func (x *KycDocument) GetIdCardBackUrl() string {
	if x != nil {
		return x.IdCardBackUrl
	}
	return ""
}

func (x *KycDocument) GetLicenseFrontUrl() string {
	if x != nil {
		return x.LicenseFrontUrl
	}
	return ""
}

func (x *KycDocument) GetLicenseBackUrl() string {
	if x != nil {
		return x.LicenseBackUrl
	}
	return ""
}

func (x *KycDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KycDocument) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *KycDocument) GetReviewerId() []byte {
	if x != nil {
		return x.ReviewerId
	}
	return nil
}

func (x *KycDocument) GetReviewedAt() string {
	if x != nil {
		return x.ReviewedAt
	}
	return ""
}

func (x *KycDocument) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KycDocument) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type KycPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycPagination) Reset() {
	*x = KycPagination{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycPagination) ProtoMessage() {}

func (x *KycPagination) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycPagination.ProtoReflect.Descriptor instead.
func (*KycPagination) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{1}
}

func (x *KycPagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *KycPagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *KycPagination) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *KycPagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SubmitKYCRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdCardNumber    string                 `protobuf:"bytes,2,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	LicenseNumber   string                 `protobuf:"bytes,3,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	IdCardFrontUrl  string                 `protobuf:"bytes,4,opt,name=id_card_front_url,json=idCardFrontUrl,proto3" json:"id_card_front_url,omitempty"`
	IdCardBackUrl   string                 `protobuf:"bytes,5,opt,name=id_card_back_url,json=idCardBackUrl,proto3" json:"id_card_back_url,omitempty"`
	LicenseFrontUrl string                 `protobuf:"bytes,6,opt,name=license_front_url,json=licenseFrontUrl,proto3" json:"license_front_url,omitempty"`
	LicenseBackUrl  string                 `protobuf:"bytes,7,opt,name=license_back_url,json=licenseBackUrl,proto3" json:"license_back_url,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Note            string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitKYCRequest) Reset() {
	*x = SubmitKYCRequest{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitKYCRequest) ProtoMessage() {}

func (x *SubmitKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitKYCRequest.ProtoReflect.Descriptor instead.
func (*SubmitKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitKYCRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *SubmitKYCRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *SubmitKYCRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *SubmitKYCRequest) GetIdCardFrontUrl() string {
	if x != nil {
		return x.IdCardFrontUrl
	}
	return ""
}

func (x *SubmitKYCRequest) GetIdCardBackUrl() string {
	if x != nil {
		return x.IdCardBackUrl
	}
	return ""
}

func (x *SubmitKYCRequest) GetLicenseFrontUrl() string {
	if x != nil {
		return x.LicenseFrontUrl
	}
	return ""
}

func (x *SubmitKYCRequest) GetLicenseBackUrl() string {
	if x != nil {
		return x.LicenseBackUrl
	}
	return ""
}

func (x *SubmitKYCRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitKYCRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type SubmitKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kyc           *KycDocument           `protobuf:"bytes,1,opt,name=kyc,proto3" json:"kyc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitKYCResponse) Reset() {
	*x = SubmitKYCResponse{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitKYCResponse) ProtoMessage() {}

func (x *SubmitKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitKYCResponse.ProtoReflect.Descriptor instead.
func (*SubmitKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitKYCResponse) GetKyc() *KycDocument {
	if x != nil {
		return x.Kyc
	}
	return nil
}

type GetKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCRequest) Reset() {
	*x = GetKYCRequest{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCRequest) ProtoMessage() {}

func (x *GetKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCRequest.ProtoReflect.Descriptor instead.
func (*GetKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetKYCRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kyc           *KycDocument           `protobuf:"bytes,1,opt,name=kyc,proto3" json:"kyc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCResponse) Reset() {
	*x = GetKYCResponse{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCResponse) ProtoMessage() {}

func (x *GetKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCResponse.ProtoReflect.Descriptor instead.
func (*GetKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetKYCResponse) GetKyc() *KycDocument {
	if x != nil {
		return x.Kyc
	}
	return nil
}

type ListPendingKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingKYCRequest) Reset() {
	*x = ListPendingKYCRequest{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingKYCRequest) ProtoMessage() {}

func (x *ListPendingKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingKYCRequest.ProtoReflect.Descriptor instead.
func (*ListPendingKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListPendingKYCRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingKYCRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPendingKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KycDocument         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *KycPagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingKYCResponse) Reset() {
	*x = ListPendingKYCResponse{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingKYCResponse) ProtoMessage() {}

func (x *ListPendingKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingKYCResponse.ProtoReflect.Descriptor instead.
func (*ListPendingKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListPendingKYCResponse) GetItems() []*KycDocument {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPendingKYCResponse) GetPagination() *KycPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReviewKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	ReviewerId    []byte                 `protobuf:"bytes,4,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewKYCRequest) Reset() {
	*x = ReviewKYCRequest{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewKYCRequest) ProtoMessage() {}

func (x *ReviewKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewKYCRequest.ProtoReflect.Descriptor instead.
func (*ReviewKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ReviewKYCRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ReviewKYCRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewKYCRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ReviewKYCRequest) GetReviewerId() []byte {
	if x != nil {
		return x.ReviewerId
	}
	return nil
}

type ReviewKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kyc           *KycDocument           `protobuf:"bytes,1,opt,name=kyc,proto3" json:"kyc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewKYCResponse) Reset() {
	*x = ReviewKYCResponse{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewKYCResponse) ProtoMessage() {}

func (x *ReviewKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewKYCResponse.ProtoReflect.Descriptor instead.
func (*ReviewKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReviewKYCResponse) GetKyc() *KycDocument {
	if x != nil {
		return x.Kyc
	}
	return nil
}

type CountPendingKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountPendingKYCRequest) Reset() {
	*x = CountPendingKYCRequest{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountPendingKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPendingKYCRequest) ProtoMessage() {}

func (x *CountPendingKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPendingKYCRequest.ProtoReflect.Descriptor instead.
func (*CountPendingKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{10}
}

type CountPendingKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountPendingKYCResponse) Reset() {
	*x = CountPendingKYCResponse{}
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountPendingKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPendingKYCResponse) ProtoMessage() {}

func (x *CountPendingKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPendingKYCResponse.ProtoReflect.Descriptor instead.
func (*CountPendingKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP(), []int{11}
}

func (x *CountPendingKYCResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_logistic_kyc_service_v1_kyc_messages_proto protoreflect.FileDescriptor

const file_logistic_kyc_service_v1_kyc_messages_proto_rawDesc = "" +
	"\n" +
	"*logistic/kyc_service/v1/kyc_messages.proto\x12\x17logistic.kyc_service.v1\"\xd9\x03\n" +
	"\vKycDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12$\n" +
	"\x0eid_card_number\x18\x03 \x01(\tR\fidCardNumber\x12%\n" +
	"\x0elicense_number\x18\x04 \x01(\tR\rlicenseNumber\x12)\n" +
	"\x11id_card_front_url\x18\x05 \x01(\tR\x0eidCardFrontUrl\x12'\n" +
	"\x10id_card_back_url\x18\x06 \x01(\tR\ridCardBackUrl\x12*\n" +
	"\x11license_front_url\x18\a \x01(\tR\x0flicenseFrontUrl\x12(\n" +
	"\x10license_back_url\x18\b \x01(\tR\x0elicenseBackUrl\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\x12\x1f\n" +
	"\vreviewer_id\x18\v \x01(\fR\n" +
	"reviewerId\x12\x1f\n" +
	"\vreviewed_at\x18\f \x01(\tR\n" +
	"reviewedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\x82\x01\n" +
	"\rKycPagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xce\x02\n" +
	"\x10SubmitKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12$\n" +
	"\x0eid_card_number\x18\x02 \x01(\tR\fidCardNumber\x12%\n" +
	"\x0elicense_number\x18\x03 \x01(\tR\rlicenseNumber\x12)\n" +
	"\x11id_card_front_url\x18\x04 \x01(\tR\x0eidCardFrontUrl\x12'\n" +
	"\x10id_card_back_url\x18\x05 \x01(\tR\ridCardBackUrl\x12*\n" +
	"\x11license_front_url\x18\x06 \x01(\tR\x0flicenseFrontUrl\x12(\n" +
	"\x10license_back_url\x18\a \x01(\tR\x0elicenseBackUrl\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\"K\n" +
	"\x11SubmitKYCResponse\x126\n" +
	"\x03kyc\x18\x01 \x01(\v2$.logistic.kyc_service.v1.KycDocumentR\x03kyc\"(\n" +
	"\rGetKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\"H\n" +
	"\x0eGetKYCResponse\x126\n" +
	"\x03kyc\x18\x01 \x01(\v2$.logistic.kyc_service.v1.KycDocumentR\x03kyc\"H\n" +
	"\x15ListPendingKYCRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x9c\x01\n" +
	"\x16ListPendingKYCResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.logistic.kyc_service.v1.KycDocumentR\x05items\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.logistic.kyc_service.v1.KycPaginationR\n" +
	"pagination\"|\n" +
	"\x10ReviewKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1f\n" +
	"\vreviewer_id\x18\x04 \x01(\fR\n" +
	"reviewerId\"K\n" +
	"\x11ReviewKYCResponse\x126\n" +
	"\x03kyc\x18\x01 \x01(\v2$.logistic.kyc_service.v1.KycDocumentR\x03kyc\"\x18\n" +
	"\x16CountPendingKYCRequest\"/\n" +
	"\x17CountPendingKYCResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05countB7Z5github.com/logistic/api/logistic/kyc_service/v1;kycv1b\x06proto3"

var (
	file_logistic_kyc_service_v1_kyc_messages_proto_rawDescOnce sync.Once
	file_logistic_kyc_service_v1_kyc_messages_proto_rawDescData []byte
)

func file_logistic_kyc_service_v1_kyc_messages_proto_rawDescGZIP() []byte {
	file_logistic_kyc_service_v1_kyc_messages_proto_rawDescOnce.Do(func() {
		file_logistic_kyc_service_v1_kyc_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logistic_kyc_service_v1_kyc_messages_proto_rawDesc), len(file_logistic_kyc_service_v1_kyc_messages_proto_rawDesc)))
	})
	return file_logistic_kyc_service_v1_kyc_messages_proto_rawDescData
}

var file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_logistic_kyc_service_v1_kyc_messages_proto_goTypes = []any{
	(*KycDocument)(nil),             // 0: logistic.kyc_service.v1.KycDocument
	(*KycPagination)(nil),           // 1: logistic.kyc_service.v1.KycPagination
	(*SubmitKYCRequest)(nil),        // 2: logistic.kyc_service.v1.SubmitKYCRequest
	(*SubmitKYCResponse)(nil),       // 3: logistic.kyc_service.v1.SubmitKYCResponse
	(*GetKYCRequest)(nil),           // 4: logistic.kyc_service.v1.GetKYCRequest
	(*GetKYCResponse)(nil),          // 5: logistic.kyc_service.v1.GetKYCResponse
	(*ListPendingKYCRequest)(nil),   // 6: logistic.kyc_service.v1.ListPendingKYCRequest
	(*ListPendingKYCResponse)(nil),  // 7: logistic.kyc_service.v1.ListPendingKYCResponse
	(*ReviewKYCRequest)(nil),        // 8: logistic.kyc_service.v1.ReviewKYCRequest
	(*ReviewKYCResponse)(nil),       // 9: logistic.kyc_service.v1.ReviewKYCResponse
	(*CountPendingKYCRequest)(nil),  // 10: logistic.kyc_service.v1.CountPendingKYCRequest
	(*CountPendingKYCResponse)(nil), // 11: logistic.kyc_service.v1.CountPendingKYCResponse
}
var file_logistic_kyc_service_v1_kyc_messages_proto_depIdxs = []int32{
	0, // 0: logistic.kyc_service.v1.SubmitKYCResponse.kyc:type_name -> logistic.kyc_service.v1.KycDocument
	0, // 1: logistic.kyc_service.v1.GetKYCResponse.kyc:type_name -> logistic.kyc_service.v1.KycDocument
	0, // 2: logistic.kyc_service.v1.ListPendingKYCResponse.items:type_name -> logistic.kyc_service.v1.KycDocument
	1, // 3: logistic.kyc_service.v1.ListPendingKYCResponse.pagination:type_name -> logistic.kyc_service.v1.KycPagination
	0, // 4: logistic.kyc_service.v1.ReviewKYCResponse.kyc:type_name -> logistic.kyc_service.v1.KycDocument
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_logistic_kyc_service_v1_kyc_messages_proto_init() }
func file_logistic_kyc_service_v1_kyc_messages_proto_init() {
	if File_logistic_kyc_service_v1_kyc_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistic_kyc_service_v1_kyc_messages_proto_rawDesc), len(file_logistic_kyc_service_v1_kyc_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logistic_kyc_service_v1_kyc_messages_proto_goTypes,
		DependencyIndexes: file_logistic_kyc_service_v1_kyc_messages_proto_depIdxs,
		MessageInfos:      file_logistic_kyc_service_v1_kyc_messages_proto_msgTypes,
	}.Build()
	File_logistic_kyc_service_v1_kyc_messages_proto = out.File
	file_logistic_kyc_service_v1_kyc_messages_proto_goTypes = nil
	file_logistic_kyc_service_v1_kyc_messages_proto_depIdxs = nil
}
