// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logistic/kyc_service/v1/kyc_service.proto

package kycv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_logistic_kyc_service_v1_kyc_service_proto protoreflect.FileDescriptor

const file_logistic_kyc_service_v1_kyc_service_proto_rawDesc = "" +
	"\n" +
	")logistic/kyc_service/v1/kyc_service.proto\x12\x17logistic.kyc_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a*logistic/kyc_service/v1/kyc_messages.proto2\xc0\x05\n" +
	"\n" +
	"KycService\x12}\n" +
	"\tSubmitKYC\x12).logistic.kyc_service.v1.SubmitKYCRequest\x1a*.logistic.kyc_service.v1.SubmitKYCResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/kyc/submit\x12t\n" +
	"\x06GetKYC\x12&.logistic.kyc_service.v1.GetKYCRequest\x1a'.logistic.kyc_service.v1.GetKYCResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/kyc/{user_id}\x12\x90\x01\n" +
	"\x0eListPendingKYC\x12..logistic.kyc_service.v1.ListPendingKYCRequest\x1a/.logistic.kyc_service.v1.ListPendingKYCResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/admin/kyc/pending\x12\x8d\x01\n" +
	"\tReviewKYC\x12).logistic.kyc_service.v1.ReviewKYCRequest\x1a*.logistic.kyc_service.v1.ReviewKYCResponse\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/admin/kyc/{user_id}/review\x12\x99\x01\n" +
	"\x0fCountPendingKYC\x12/.logistic.kyc_service.v1.CountPendingKYCRequest\x1a0.logistic.kyc_service.v1.CountPendingKYCResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/admin/kyc/count-pendingB7Z5github.com/logistic/api/logistic/kyc_service/v1;kycv1b\x06proto3"

var file_logistic_kyc_service_v1_kyc_service_proto_goTypes = []any{
	(*SubmitKYCRequest)(nil),        // 0: logistic.kyc_service.v1.SubmitKYCRequest
	(*GetKYCRequest)(nil),           // 1: logistic.kyc_service.v1.GetKYCRequest
	(*ListPendingKYCRequest)(nil),   // 2: logistic.kyc_service.v1.ListPendingKYCRequest
	(*ReviewKYCRequest)(nil),        // 3: logistic.kyc_service.v1.ReviewKYCRequest
	(*CountPendingKYCRequest)(nil),  // 4: logistic.kyc_service.v1.CountPendingKYCRequest
	(*SubmitKYCResponse)(nil),       // 5: logistic.kyc_service.v1.SubmitKYCResponse
	(*GetKYCResponse)(nil),          // 6: logistic.kyc_service.v1.GetKYCResponse
	(*ListPendingKYCResponse)(nil),  // 7: logistic.kyc_service.v1.ListPendingKYCResponse
	(*ReviewKYCResponse)(nil),       // 8: logistic.kyc_service.v1.ReviewKYCResponse
	(*CountPendingKYCResponse)(nil), // 9: logistic.kyc_service.v1.CountPendingKYCResponse
}
var file_logistic_kyc_service_v1_kyc_service_proto_depIdxs = []int32{
	0, // 0: logistic.kyc_service.v1.KycService.SubmitKYC:input_type -> logistic.kyc_service.v1.SubmitKYCRequest
	1, // 1: logistic.kyc_service.v1.KycService.GetKYC:input_type -> logistic.kyc_service.v1.GetKYCRequest
	2, // 2: logistic.kyc_service.v1.KycService.ListPendingKYC:input_type -> logistic.kyc_service.v1.ListPendingKYCRequest
	3, // 3: logistic.kyc_service.v1.KycService.ReviewKYC:input_type -> logistic.kyc_service.v1.ReviewKYCRequest
	4, // 4: logistic.kyc_service.v1.KycService.CountPendingKYC:input_type -> logistic.kyc_service.v1.CountPendingKYCRequest
	5, // 5: logistic.kyc_service.v1.KycService.SubmitKYC:output_type -> logistic.kyc_service.v1.SubmitKYCResponse
	6, // 6: logistic.kyc_service.v1.KycService.GetKYC:output_type -> logistic.kyc_service.v1.GetKYCResponse
	7, // 7: logistic.kyc_service.v1.KycService.ListPendingKYC:output_type -> logistic.kyc_service.v1.ListPendingKYCResponse
	8, // 8: logistic.kyc_service.v1.KycService.ReviewKYC:output_type -> logistic.kyc_service.v1.ReviewKYCResponse
	9, // 9: logistic.kyc_service.v1.KycService.CountPendingKYC:output_type -> logistic.kyc_service.v1.CountPendingKYCResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logistic_kyc_service_v1_kyc_service_proto_init() }
func file_logistic_kyc_service_v1_kyc_service_proto_init() {
	if File_logistic_kyc_service_v1_kyc_service_proto != nil {
		return
	}
	file_logistic_kyc_service_v1_kyc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistic_kyc_service_v1_kyc_service_proto_rawDesc), len(file_logistic_kyc_service_v1_kyc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistic_kyc_service_v1_kyc_service_proto_goTypes,
		DependencyIndexes: file_logistic_kyc_service_v1_kyc_service_proto_depIdxs,
	}.Build()
	File_logistic_kyc_service_v1_kyc_service_proto = out.File
	file_logistic_kyc_service_v1_kyc_service_proto_goTypes = nil
	file_logistic_kyc_service_v1_kyc_service_proto_depIdxs = nil
}
