// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: logistic/kyc_service/v1/kyc_service.proto

package kycv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KycService_SubmitKYC_FullMethodName       = "/logistic.kyc_service.v1.KycService/SubmitKYC"
	KycService_GetKYC_FullMethodName          = "/logistic.kyc_service.v1.KycService/GetKYC"
	KycService_ListPendingKYC_FullMethodName  = "/logistic.kyc_service.v1.KycService/ListPendingKYC"
	KycService_ReviewKYC_FullMethodName       = "/logistic.kyc_service.v1.KycService/ReviewKYC"
	KycService_CountPendingKYC_FullMethodName = "/logistic.kyc_service.v1.KycService/CountPendingKYC"
)

// KycServiceClient is the client API for KycService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KycServiceClient interface {
	SubmitKYC(ctx context.Context, in *SubmitKYCRequest, opts ...grpc.CallOption) (*SubmitKYCResponse, error)
	GetKYC(ctx context.Context, in *GetKYCRequest, opts ...grpc.CallOption) (*GetKYCResponse, error)
	ListPendingKYC(ctx context.Context, in *ListPendingKYCRequest, opts ...grpc.CallOption) (*ListPendingKYCResponse, error)
	ReviewKYC(ctx context.Context, in *ReviewKYCRequest, opts ...grpc.CallOption) (*ReviewKYCResponse, error)
	CountPendingKYC(ctx context.Context, in *CountPendingKYCRequest, opts ...grpc.CallOption) (*CountPendingKYCResponse, error)
}

type kycServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKycServiceClient(cc grpc.ClientConnInterface) KycServiceClient {
	return &kycServiceClient{cc}
}

func (c *kycServiceClient) SubmitKYC(ctx context.Context, in *SubmitKYCRequest, opts ...grpc.CallOption) (*SubmitKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitKYCResponse)
	err := c.cc.Invoke(ctx, KycService_SubmitKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) GetKYC(ctx context.Context, in *GetKYCRequest, opts ...grpc.CallOption) (*GetKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCResponse)
	err := c.cc.Invoke(ctx, KycService_GetKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) ListPendingKYC(ctx context.Context, in *ListPendingKYCRequest, opts ...grpc.CallOption) (*ListPendingKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingKYCResponse)
	err := c.cc.Invoke(ctx, KycService_ListPendingKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) ReviewKYC(ctx context.Context, in *ReviewKYCRequest, opts ...grpc.CallOption) (*ReviewKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewKYCResponse)
	err := c.cc.Invoke(ctx, KycService_ReviewKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) CountPendingKYC(ctx context.Context, in *CountPendingKYCRequest, opts ...grpc.CallOption) (*CountPendingKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountPendingKYCResponse)
	err := c.cc.Invoke(ctx, KycService_CountPendingKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KycServiceServer is the server API for KycService service.
// All implementations must embed UnimplementedKycServiceServer
// for forward compatibility.
type KycServiceServer interface {
	SubmitKYC(context.Context, *SubmitKYCRequest) (*SubmitKYCResponse, error)
	GetKYC(context.Context, *GetKYCRequest) (*GetKYCResponse, error)
	ListPendingKYC(context.Context, *ListPendingKYCRequest) (*ListPendingKYCResponse, error)
	ReviewKYC(context.Context, *ReviewKYCRequest) (*ReviewKYCResponse, error)
	CountPendingKYC(context.Context, *CountPendingKYCRequest) (*CountPendingKYCResponse, error)
	mustEmbedUnimplementedKycServiceServer()
}

// UnimplementedKycServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKycServiceServer struct{}

func (UnimplementedKycServiceServer) SubmitKYC(context.Context, *SubmitKYCRequest) (*SubmitKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitKYC not implemented")
}
func (UnimplementedKycServiceServer) GetKYC(context.Context, *GetKYCRequest) (*GetKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKYC not implemented")
}
func (UnimplementedKycServiceServer) ListPendingKYC(context.Context, *ListPendingKYCRequest) (*ListPendingKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingKYC not implemented")
}
func (UnimplementedKycServiceServer) ReviewKYC(context.Context, *ReviewKYCRequest) (*ReviewKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewKYC not implemented")
}
func (UnimplementedKycServiceServer) CountPendingKYC(context.Context, *CountPendingKYCRequest) (*CountPendingKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountPendingKYC not implemented")
}
func (UnimplementedKycServiceServer) mustEmbedUnimplementedKycServiceServer() {}
func (UnimplementedKycServiceServer) testEmbeddedByValue()                    {}

// UnsafeKycServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KycServiceServer will
// result in compilation errors.
type UnsafeKycServiceServer interface {
	mustEmbedUnimplementedKycServiceServer()
}

func RegisterKycServiceServer(s grpc.ServiceRegistrar, srv KycServiceServer) {
	// If the following call panics, it indicates UnimplementedKycServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KycService_ServiceDesc, srv)
}

func _KycService_SubmitKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).SubmitKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_SubmitKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).SubmitKYC(ctx, req.(*SubmitKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_GetKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).GetKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_GetKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).GetKYC(ctx, req.(*GetKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_ListPendingKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).ListPendingKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_ListPendingKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).ListPendingKYC(ctx, req.(*ListPendingKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_ReviewKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).ReviewKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_ReviewKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).ReviewKYC(ctx, req.(*ReviewKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_CountPendingKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountPendingKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).CountPendingKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_CountPendingKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).CountPendingKYC(ctx, req.(*CountPendingKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KycService_ServiceDesc is the grpc.ServiceDesc for KycService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KycService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logistic.kyc_service.v1.KycService",
	HandlerType: (*KycServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitKYC",
			Handler:    _KycService_SubmitKYC_Handler,
		},
		{
			MethodName: "GetKYC",
			Handler:    _KycService_GetKYC_Handler,
		},
		{
			MethodName: "ListPendingKYC",
			Handler:    _KycService_ListPendingKYC_Handler,
		},
		{
			MethodName: "ReviewKYC",
			Handler:    _KycService_ReviewKYC_Handler,
		},
		{
			MethodName: "CountPendingKYC",
			Handler:    _KycService_CountPendingKYC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logistic/kyc_service/v1/kyc_service.proto",
}
